---
- name: API Call with Ansible
  hosts: all
  vars_files:
    - group_vars/vault.yml
  gather_facts: false
  tasks:
     
    - name: Get repositories
      uri:
        url: https://api.github.com/repos/moisdv/
        return_content: true 
        headers:
          Accept: application/vnd.github+json
          Authorization: Bearer {{ authToken }}
          X-GitHub-Api-Version: 2022-11-28
      register: outputt

    - name: debug
      debug:
        var: outputt
